### ISSUE TITLE
Ljpeg encode parameters

### ISSUE THREAD

**Issue by schoolpost** [brilliantimagery/brilliantimagery#25]
Curious why you opted for a 3d array for input into the encode function, instead of typically bytearray?

How is this function used? 

Let’s say I have a 4000x3000 16 bit Bayer image array

We pass a 1x4000x3000 array into the function? Each pixel value in the first dimension?

When I run the encode it spits back and array of the same size and length and with dtype int32? Shouldn’t simply be simple byte array? Otherwise how is compression happening?

Just looking to understand it, thanks

**Comment by clipclapclop** [comment]
While the ljpeg module is written to be able to operate independently of the others, it's optimized to work as part of the BrilliantImagery project.

When I had 1D arrays I was constantly having to convert between pixel location/color channel to array index and back. It was messy. Now the location and channel are the array index. I find it much more readable and maintainable (although it clearly needs better documentation which is one of the next things on my TODO list).

DNGs can deal with various precisions. It was simplest to just pic a fixed precision that was greater than DNGs allow and not have to constantly be converting between bits or bytes and ints. Additionally, the Cython docs say it's fastest when working with intc which, for me, is an int32. The intention is to convert to int32s at the beginning of the process, do all the processing as quickly as possible, and then convert to whatever's needed.

If you're passing the data in an unexpected format, which you seem to be doing unless it's a monochromatic image (which I assume yours isn't since such images don't need bayer masks), then I don't know what it will do or why it does it.

Not knowing the details of your data I don't know how it needs to be formatted but for a typical DNG with a typical 2x2 bayer mask, you'd treat alternating rows as alternating color channels and ignore the fact that there are two colors per row so it'd be a 2x4000x1500 array that you pass into the encoder function (along with the other inputs) if I'm remembering correctly (it's been a while since I've thought about some of these low-level details).
